module.exports = {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"type-empty": [2, "never"],
		"type-case": [2, "always", "lower-case"],
		"type-enum": [
			2,
			"always",
			[
				"build",
				"chore",
				"ci",
				"docs",
				"feat",
				"fix",
				"perf",
				"refactor",
				"revert",
				"style",
				"test",
			],
		],
		"scope-empty": [2, "always"],
		"scope-case": [2, "always", "lower-case"],
		"subject-empty": [2, "never"],
		"subject-full-stop": [2, "never", "."],
		"subject-case": [
			2,
			"never",
			["sentence-case", "start-case", "pascal-case", "upper-case"],
		],
		"header-max-length": [2, "always", 100],
		"body-leading-blank": [1, "always"],
		"footer-leading-blank": [1, "always"],
	},
};
